package hk.linktech.framework.test.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradeWorksExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    protected int start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    protected int limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public TradeWorksExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("_orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("_orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("_orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("_orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("_orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("_orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("_orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("_orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("_orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("_orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("_orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("_orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("_mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("_mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("_mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("_mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("_mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("_mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("_mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("_mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("_mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("_mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("_mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("_mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("_mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andChconpropriceIsNull() {
            addCriterion("_chConProPrice is null");
            return (Criteria) this;
        }

        public Criteria andChconpropriceIsNotNull() {
            addCriterion("_chConProPrice is not null");
            return (Criteria) this;
        }

        public Criteria andChconpropriceEqualTo(Long value) {
            addCriterion("_chConProPrice =", value, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceNotEqualTo(Long value) {
            addCriterion("_chConProPrice <>", value, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceGreaterThan(Long value) {
            addCriterion("_chConProPrice >", value, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceGreaterThanOrEqualTo(Long value) {
            addCriterion("_chConProPrice >=", value, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceLessThan(Long value) {
            addCriterion("_chConProPrice <", value, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceLessThanOrEqualTo(Long value) {
            addCriterion("_chConProPrice <=", value, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceIn(List<Long> values) {
            addCriterion("_chConProPrice in", values, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceNotIn(List<Long> values) {
            addCriterion("_chConProPrice not in", values, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceBetween(Long value1, Long value2) {
            addCriterion("_chConProPrice between", value1, value2, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconpropriceNotBetween(Long value1, Long value2) {
            addCriterion("_chConProPrice not between", value1, value2, "chconproprice");
            return (Criteria) this;
        }

        public Criteria andChconproquantityIsNull() {
            addCriterion("_chConProQuantity is null");
            return (Criteria) this;
        }

        public Criteria andChconproquantityIsNotNull() {
            addCriterion("_chConProQuantity is not null");
            return (Criteria) this;
        }

        public Criteria andChconproquantityEqualTo(Integer value) {
            addCriterion("_chConProQuantity =", value, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityNotEqualTo(Integer value) {
            addCriterion("_chConProQuantity <>", value, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityGreaterThan(Integer value) {
            addCriterion("_chConProQuantity >", value, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("_chConProQuantity >=", value, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityLessThan(Integer value) {
            addCriterion("_chConProQuantity <", value, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityLessThanOrEqualTo(Integer value) {
            addCriterion("_chConProQuantity <=", value, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityIn(List<Integer> values) {
            addCriterion("_chConProQuantity in", values, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityNotIn(List<Integer> values) {
            addCriterion("_chConProQuantity not in", values, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityBetween(Integer value1, Integer value2) {
            addCriterion("_chConProQuantity between", value1, value2, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andChconproquantityNotBetween(Integer value1, Integer value2) {
            addCriterion("_chConProQuantity not between", value1, value2, "chconproquantity");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("_status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("_status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("_status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("_status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("_status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("_status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("_status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("_status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("_status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("_status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("_status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("_status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("_createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("_createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("_createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("_createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("_createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("_createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("_createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("_createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("_createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("_createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andAgidIsNull() {
            addCriterion("_agId is null");
            return (Criteria) this;
        }

        public Criteria andAgidIsNotNull() {
            addCriterion("_agId is not null");
            return (Criteria) this;
        }

        public Criteria andAgidEqualTo(Integer value) {
            addCriterion("_agId =", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidNotEqualTo(Integer value) {
            addCriterion("_agId <>", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidGreaterThan(Integer value) {
            addCriterion("_agId >", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidGreaterThanOrEqualTo(Integer value) {
            addCriterion("_agId >=", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidLessThan(Integer value) {
            addCriterion("_agId <", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidLessThanOrEqualTo(Integer value) {
            addCriterion("_agId <=", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidIn(List<Integer> values) {
            addCriterion("_agId in", values, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidNotIn(List<Integer> values) {
            addCriterion("_agId not in", values, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidBetween(Integer value1, Integer value2) {
            addCriterion("_agId between", value1, value2, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidNotBetween(Integer value1, Integer value2) {
            addCriterion("_agId not between", value1, value2, "agid");
            return (Criteria) this;
        }

        public Criteria andChidIsNull() {
            addCriterion("_chId is null");
            return (Criteria) this;
        }

        public Criteria andChidIsNotNull() {
            addCriterion("_chId is not null");
            return (Criteria) this;
        }

        public Criteria andChidEqualTo(Integer value) {
            addCriterion("_chId =", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotEqualTo(Integer value) {
            addCriterion("_chId <>", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidGreaterThan(Integer value) {
            addCriterion("_chId >", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidGreaterThanOrEqualTo(Integer value) {
            addCriterion("_chId >=", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidLessThan(Integer value) {
            addCriterion("_chId <", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidLessThanOrEqualTo(Integer value) {
            addCriterion("_chId <=", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidIn(List<Integer> values) {
            addCriterion("_chId in", values, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotIn(List<Integer> values) {
            addCriterion("_chId not in", values, "chid");
            return (Criteria) this;
        }

        public Criteria andChidBetween(Integer value1, Integer value2) {
            addCriterion("_chId between", value1, value2, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotBetween(Integer value1, Integer value2) {
            addCriterion("_chId not between", value1, value2, "chid");
            return (Criteria) this;
        }

        public Criteria andChorderidIsNull() {
            addCriterion("_chOrderId is null");
            return (Criteria) this;
        }

        public Criteria andChorderidIsNotNull() {
            addCriterion("_chOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andChorderidEqualTo(String value) {
            addCriterion("_chOrderId =", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotEqualTo(String value) {
            addCriterion("_chOrderId <>", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidGreaterThan(String value) {
            addCriterion("_chOrderId >", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidGreaterThanOrEqualTo(String value) {
            addCriterion("_chOrderId >=", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidLessThan(String value) {
            addCriterion("_chOrderId <", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidLessThanOrEqualTo(String value) {
            addCriterion("_chOrderId <=", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidLike(String value) {
            addCriterion("_chOrderId like", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotLike(String value) {
            addCriterion("_chOrderId not like", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidIn(List<String> values) {
            addCriterion("_chOrderId in", values, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotIn(List<String> values) {
            addCriterion("_chOrderId not in", values, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidBetween(String value1, String value2) {
            addCriterion("_chOrderId between", value1, value2, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotBetween(String value1, String value2) {
            addCriterion("_chOrderId not between", value1, value2, "chorderid");
            return (Criteria) this;
        }

        public Criteria andNettypeIsNull() {
            addCriterion("_netType is null");
            return (Criteria) this;
        }

        public Criteria andNettypeIsNotNull() {
            addCriterion("_netType is not null");
            return (Criteria) this;
        }

        public Criteria andNettypeEqualTo(Integer value) {
            addCriterion("_netType =", value, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeNotEqualTo(Integer value) {
            addCriterion("_netType <>", value, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeGreaterThan(Integer value) {
            addCriterion("_netType >", value, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("_netType >=", value, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeLessThan(Integer value) {
            addCriterion("_netType <", value, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeLessThanOrEqualTo(Integer value) {
            addCriterion("_netType <=", value, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeIn(List<Integer> values) {
            addCriterion("_netType in", values, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeNotIn(List<Integer> values) {
            addCriterion("_netType not in", values, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeBetween(Integer value1, Integer value2) {
            addCriterion("_netType between", value1, value2, "nettype");
            return (Criteria) this;
        }

        public Criteria andNettypeNotBetween(Integer value1, Integer value2) {
            addCriterion("_netType not between", value1, value2, "nettype");
            return (Criteria) this;
        }

        public Criteria andCardproviceIsNull() {
            addCriterion("_cardProvice is null");
            return (Criteria) this;
        }

        public Criteria andCardproviceIsNotNull() {
            addCriterion("_cardProvice is not null");
            return (Criteria) this;
        }

        public Criteria andCardproviceEqualTo(Integer value) {
            addCriterion("_cardProvice =", value, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceNotEqualTo(Integer value) {
            addCriterion("_cardProvice <>", value, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceGreaterThan(Integer value) {
            addCriterion("_cardProvice >", value, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceGreaterThanOrEqualTo(Integer value) {
            addCriterion("_cardProvice >=", value, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceLessThan(Integer value) {
            addCriterion("_cardProvice <", value, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceLessThanOrEqualTo(Integer value) {
            addCriterion("_cardProvice <=", value, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceIn(List<Integer> values) {
            addCriterion("_cardProvice in", values, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceNotIn(List<Integer> values) {
            addCriterion("_cardProvice not in", values, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceBetween(Integer value1, Integer value2) {
            addCriterion("_cardProvice between", value1, value2, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andCardproviceNotBetween(Integer value1, Integer value2) {
            addCriterion("_cardProvice not between", value1, value2, "cardprovice");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeIsNull() {
            addCriterion("_detailsErrorCode is null");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeIsNotNull() {
            addCriterion("_detailsErrorCode is not null");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeEqualTo(String value) {
            addCriterion("_detailsErrorCode =", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeNotEqualTo(String value) {
            addCriterion("_detailsErrorCode <>", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeGreaterThan(String value) {
            addCriterion("_detailsErrorCode >", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeGreaterThanOrEqualTo(String value) {
            addCriterion("_detailsErrorCode >=", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeLessThan(String value) {
            addCriterion("_detailsErrorCode <", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeLessThanOrEqualTo(String value) {
            addCriterion("_detailsErrorCode <=", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeLike(String value) {
            addCriterion("_detailsErrorCode like", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeNotLike(String value) {
            addCriterion("_detailsErrorCode not like", value, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeIn(List<String> values) {
            addCriterion("_detailsErrorCode in", values, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeNotIn(List<String> values) {
            addCriterion("_detailsErrorCode not in", values, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeBetween(String value1, String value2) {
            addCriterion("_detailsErrorCode between", value1, value2, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrorcodeNotBetween(String value1, String value2) {
            addCriterion("_detailsErrorCode not between", value1, value2, "detailserrorcode");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgIsNull() {
            addCriterion("_detailsErrorMsg is null");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgIsNotNull() {
            addCriterion("_detailsErrorMsg is not null");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgEqualTo(String value) {
            addCriterion("_detailsErrorMsg =", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgNotEqualTo(String value) {
            addCriterion("_detailsErrorMsg <>", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgGreaterThan(String value) {
            addCriterion("_detailsErrorMsg >", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgGreaterThanOrEqualTo(String value) {
            addCriterion("_detailsErrorMsg >=", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgLessThan(String value) {
            addCriterion("_detailsErrorMsg <", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgLessThanOrEqualTo(String value) {
            addCriterion("_detailsErrorMsg <=", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgLike(String value) {
            addCriterion("_detailsErrorMsg like", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgNotLike(String value) {
            addCriterion("_detailsErrorMsg not like", value, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgIn(List<String> values) {
            addCriterion("_detailsErrorMsg in", values, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgNotIn(List<String> values) {
            addCriterion("_detailsErrorMsg not in", values, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgBetween(String value1, String value2) {
            addCriterion("_detailsErrorMsg between", value1, value2, "detailserrormsg");
            return (Criteria) this;
        }

        public Criteria andDetailserrormsgNotBetween(String value1, String value2) {
            addCriterion("_detailsErrorMsg not between", value1, value2, "detailserrormsg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _trade_works
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _trade_works
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}