package hk.linktech.framework.test.bean;

import java.util.Date;

public class TradeWorks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._chConProPrice
     *
     * @mbggenerated
     */
    private Long chconproprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._chConProQuantity
     *
     * @mbggenerated
     */
    private Integer chconproquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._agId
     *
     * @mbggenerated
     */
    private Integer agid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._chId
     *
     * @mbggenerated
     */
    private Integer chid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._chOrderId
     *
     * @mbggenerated
     */
    private String chorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._netType
     *
     * @mbggenerated
     */
    private Integer nettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._cardProvice
     *
     * @mbggenerated
     */
    private Integer cardprovice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._detailsErrorCode
     *
     * @mbggenerated
     */
    private String detailserrorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _trade_works._detailsErrorMsg
     *
     * @mbggenerated
     */
    private String detailserrormsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._id
     *
     * @return the value of _trade_works._id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._id
     *
     * @param id the value for _trade_works._id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._orderId
     *
     * @return the value of _trade_works._orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._orderId
     *
     * @param orderid the value for _trade_works._orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._mobile
     *
     * @return the value of _trade_works._mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._mobile
     *
     * @param mobile the value for _trade_works._mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._chConProPrice
     *
     * @return the value of _trade_works._chConProPrice
     *
     * @mbggenerated
     */
    public Long getChconproprice() {
        return chconproprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._chConProPrice
     *
     * @param chconproprice the value for _trade_works._chConProPrice
     *
     * @mbggenerated
     */
    public void setChconproprice(Long chconproprice) {
        this.chconproprice = chconproprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._chConProQuantity
     *
     * @return the value of _trade_works._chConProQuantity
     *
     * @mbggenerated
     */
    public Integer getChconproquantity() {
        return chconproquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._chConProQuantity
     *
     * @param chconproquantity the value for _trade_works._chConProQuantity
     *
     * @mbggenerated
     */
    public void setChconproquantity(Integer chconproquantity) {
        this.chconproquantity = chconproquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._status
     *
     * @return the value of _trade_works._status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._status
     *
     * @param status the value for _trade_works._status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._createTime
     *
     * @return the value of _trade_works._createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._createTime
     *
     * @param createtime the value for _trade_works._createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._agId
     *
     * @return the value of _trade_works._agId
     *
     * @mbggenerated
     */
    public Integer getAgid() {
        return agid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._agId
     *
     * @param agid the value for _trade_works._agId
     *
     * @mbggenerated
     */
    public void setAgid(Integer agid) {
        this.agid = agid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._chId
     *
     * @return the value of _trade_works._chId
     *
     * @mbggenerated
     */
    public Integer getChid() {
        return chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._chId
     *
     * @param chid the value for _trade_works._chId
     *
     * @mbggenerated
     */
    public void setChid(Integer chid) {
        this.chid = chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._chOrderId
     *
     * @return the value of _trade_works._chOrderId
     *
     * @mbggenerated
     */
    public String getChorderid() {
        return chorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._chOrderId
     *
     * @param chorderid the value for _trade_works._chOrderId
     *
     * @mbggenerated
     */
    public void setChorderid(String chorderid) {
        this.chorderid = chorderid == null ? null : chorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._netType
     *
     * @return the value of _trade_works._netType
     *
     * @mbggenerated
     */
    public Integer getNettype() {
        return nettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._netType
     *
     * @param nettype the value for _trade_works._netType
     *
     * @mbggenerated
     */
    public void setNettype(Integer nettype) {
        this.nettype = nettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._cardProvice
     *
     * @return the value of _trade_works._cardProvice
     *
     * @mbggenerated
     */
    public Integer getCardprovice() {
        return cardprovice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._cardProvice
     *
     * @param cardprovice the value for _trade_works._cardProvice
     *
     * @mbggenerated
     */
    public void setCardprovice(Integer cardprovice) {
        this.cardprovice = cardprovice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._detailsErrorCode
     *
     * @return the value of _trade_works._detailsErrorCode
     *
     * @mbggenerated
     */
    public String getDetailserrorcode() {
        return detailserrorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._detailsErrorCode
     *
     * @param detailserrorcode the value for _trade_works._detailsErrorCode
     *
     * @mbggenerated
     */
    public void setDetailserrorcode(String detailserrorcode) {
        this.detailserrorcode = detailserrorcode == null ? null : detailserrorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _trade_works._detailsErrorMsg
     *
     * @return the value of _trade_works._detailsErrorMsg
     *
     * @mbggenerated
     */
    public String getDetailserrormsg() {
        return detailserrormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _trade_works._detailsErrorMsg
     *
     * @param detailserrormsg the value for _trade_works._detailsErrorMsg
     *
     * @mbggenerated
     */
    public void setDetailserrormsg(String detailserrormsg) {
        this.detailserrormsg = detailserrormsg == null ? null : detailserrormsg.trim();
    }
}